#!/usr/bin/env bash
set -euo pipefail

version="${1:?version required}"
checksums="${2:?checksums file required}"
output="${3:?output file required}"
repo="layergrid/layergrid-cli"
version_no_v="${version#v}"
base="https://github.com/${repo}/releases/download/${version}"

sha_for() {
  local artifact="$1"
  awk -v artifact="$artifact" '$2 == artifact { print $1 }' "$checksums"
}

darwin_amd64="layergrid_${version_no_v}_darwin_amd64.tar.gz"
darwin_arm64="layergrid_${version_no_v}_darwin_arm64.tar.gz"
linux_amd64="layergrid_${version_no_v}_linux_amd64.tar.gz"
linux_arm64="layergrid_${version_no_v}_linux_arm64.tar.gz"

darwin_amd64_sha="$(sha_for "$darwin_amd64")"
darwin_arm64_sha="$(sha_for "$darwin_arm64")"
linux_amd64_sha="$(sha_for "$linux_amd64")"
linux_arm64_sha="$(sha_for "$linux_arm64")"

for value in "$darwin_amd64_sha" "$darwin_arm64_sha" "$linux_amd64_sha" "$linux_arm64_sha"; do
  if [[ -z "$value" ]]; then
    echo "missing checksum in $checksums" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "$output")"
cat >"$output" <<FORMULA
# This file was generated by layergrid/layergrid-cli. DO NOT EDIT.
class Layergrid < Formula
  desc "Offline static scanner for AI agent stack trifecta risks"
  homepage "https://github.com/layergrid/layergrid-cli"
  version "${version_no_v}"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "${base}/${darwin_amd64}"
      sha256 "${darwin_amd64_sha}"
    end
    on_arm do
      url "${base}/${darwin_arm64}"
      sha256 "${darwin_arm64_sha}"
    end
  end

  on_linux do
    on_intel do
      url "${base}/${linux_amd64}"
      sha256 "${linux_amd64_sha}"
    end
    on_arm do
      url "${base}/${linux_arm64}"
      sha256 "${linux_arm64_sha}"
    end
  end

  def install
    bin.install "layergrid"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/layergrid version")
  end
end
FORMULA
